import { STTProvider, TranscribeOptions } from "../types";
import { Transcript } from "@/types";
import { generateId } from "@/lib/utils";

export class MockSTTProvider implements STTProvider {
  name = "Mock / Demo Provider";

  async transcribe(_audio: ArrayBuffer | Buffer | string, options?: TranscribeOptions): Promise<Transcript> {
    return {
      id: `tr-${generateId()}`,
      language: options?.language || "en",
      duration: 35,
      fullText:
        "Welcome to Unclip. This is a high-fidelity mock transcription generated by the built-in STT engine. Unclip allows you to extract precise timestamped speech from Instagram videos.",
      segments: [
        {
          id: "seg-mock-1",
          start: 0.0,
          end: 4.5,
          text: "Welcome to Unclip.",
          speaker: "Speaker 1",
          confidence: 0.99,
        },
        {
          id: "seg-mock-2",
          start: 4.8,
          end: 18.2,
          text: "This is a high-fidelity mock transcription generated by the built-in STT engine.",
          speaker: "Speaker 1",
          confidence: 0.97,
        },
        {
          id: "seg-mock-3",
          start: 18.8,
          end: 35.0,
          text: "Unclip allows you to extract precise timestamped speech from Instagram videos.",
          speaker: "Speaker 1",
          confidence: 0.98,
        },
      ],
      metadata: {
        title: options?.title || "Sample Transcription",
        sourceUrl: options?.sourceUrl,
        createdAt: new Date().toISOString(),
        sttProvider: "Local Whisper (whisper.cpp - ggml-large-v3-turbo)",
      },
    };
  }
}
